// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class ClgListInstiView
    {
        [Column("CompanyID")]
        public int CompanyId { get; set; }
        [Required]
        [StringLength(4)]
        public string EntityName { get; set; }
        [Column("EntityID")]
        public int EntityId { get; set; }
        [StringLength(100)]
        public string CompName { get; set; }
        [StringLength(500)]
        public string Address { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [StringLength(50)]
        public string State { get; set; }
        [StringLength(50)]
        public string Country { get; set; }
        [StringLength(200)]
        public string Phnum { get; set; }
        [StringLength(50)]
        public string Web { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [Column("TCLogo", TypeName = "image")]
        public byte[] Tclogo { get; set; }
        [StringLength(50)]
        public string CompCode { get; set; }
        public string CollegePros { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public string PrincipalMessageText { get; set; }
        [Column("PrincipalMessageHTML")]
        public string PrincipalMessageHtml { get; set; }
        [Column("PrincipalPersonID")]
        public int? PrincipalPersonId { get; set; }
        [Column("HRStartDate", TypeName = "datetime")]
        public DateTime? HrstartDate { get; set; }
        [Column("MainPartyID")]
        public int? MainPartyId { get; set; }
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        [StringLength(818)]
        public string FullName { get; set; }
        [Column(TypeName = "image")]
        public byte[] PicPerson { get; set; }
    }
}