// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class ClgListPersonsView
    {
        [Column("PersonID")]
        public int PersonId { get; set; }
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column("DeptID")]
        public int? DeptId { get; set; }
        [StringLength(100)]
        public string Occupation { get; set; }
        public int? DeptRank { get; set; }
        [StringLength(50)]
        public string Desig { get; set; }
        [Required]
        [StringLength(818)]
        public string FullName { get; set; }
        [StringLength(100)]
        public string Education { get; set; }
        [StringLength(255)]
        public string Email { get; set; }
        [StringLength(255)]
        public string CellNum { get; set; }
        [Column("UserID")]
        public Guid? UserId { get; set; }
        [StringLength(70)]
        public string Fmode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Sdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Edate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommSdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommEdate { get; set; }
        public int? StaffMode { get; set; }
        public int? NonTechStaffRank { get; set; }
        public bool? NonTeacStaff { get; set; }
        [StringLength(200)]
        public string StaffDept { get; set; }
        public string Committee { get; set; }
        [StringLength(70)]
        public string DeptName { get; set; }
        public int? EstabYear { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        public int? RoleId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Dated { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? CreatedOn { get; set; }
        public int? Companyid { get; set; }
        public bool? IsStudent { get; set; }
        public string ImageUrl { get; set; }
        [StringLength(1000)]
        public string TopQual { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}