// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class ClgListNaaC
    {
        [Column("NaacID")]
        public int NaacId { get; set; }
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column("CompanyID")]
        public int? CompanyId { get; set; }
        [Column("IQAC")]
        public string Iqac { get; set; }
        [Column("AQAR")]
        public string Aqar { get; set; }
        [Column("SSR")]
        public string Ssr { get; set; }
        public string AgendaMinutes { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [Column("FinyearID")]
        public int? FinyearId { get; set; }
        [StringLength(100)]
        public string CompName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EnDate { get; set; }
        [StringLength(61)]
        public string Descrip { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}