// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class ClgListEventDetailView
    {
        [Column("EventID")]
        public int EventId { get; set; }
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column("CompanyID")]
        public int? CompanyId { get; set; }
        [Column("DeptID")]
        public int? DeptId { get; set; }
        [StringLength(100)]
        public string EventName { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Sdate { get; set; }
        [StringLength(50)]
        public string EventType { get; set; }
        [StringLength(50)]
        public string CompCode { get; set; }
        [StringLength(1000)]
        public string EventTypeDescrip { get; set; }
        [StringLength(70)]
        public string DeptName { get; set; }
        public int? EstabYear { get; set; }
        [Column("HODPersonID")]
        public int? HodpersonId { get; set; }
        [Column("HODName")]
        [StringLength(818)]
        public string Hodname { get; set; }
        [StringLength(100)]
        public string CompName { get; set; }
        public string Summary { get; set; }
        [StringLength(50)]
        public string Place { get; set; }
        [Column(TypeName = "ntext")]
        public string EventText { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreatedOn { get; set; }
        public string DescriptionText { get; set; }
        public string Brochure { get; set; }
        [StringLength(250)]
        public string Participant { get; set; }
        [StringLength(100)]
        public string Speaker { get; set; }
        [StringLength(100)]
        public string OrganizedBy { get; set; }
        [Column("PurposeHTML")]
        public string PurposeHtml { get; set; }
        public string PurposeText { get; set; }
        [StringLength(61)]
        public string Descrip { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}