// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class ClgListDepartmentView
    {
        [Column("DeptID")]
        public int DeptId { get; set; }
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column("CompanyID")]
        public int CompanyId { get; set; }
        [StringLength(70)]
        public string DeptName { get; set; }
        [Column("HODPersonID")]
        public int? HodpersonId { get; set; }
        public int? EstabYear { get; set; }
        [Column("HODName")]
        [StringLength(818)]
        public string Hodname { get; set; }
        [StringLength(100)]
        public string Education { get; set; }
        [StringLength(100)]
        public string CompName { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [StringLength(50)]
        public string CompCode { get; set; }
        [StringLength(50)]
        public string DepCode { get; set; }
        public string ImageUrl { get; set; }
        [Column("PersonID")]
        public int? PersonId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}