// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class ClgListSubjectView
    {
        [Column("SubjectID")]
        public int SubjectId { get; set; }
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column("DeptID")]
        public int? DeptId { get; set; }
        [Column("DegreeCourseID")]
        public int? DegreeCourseId { get; set; }
        public string SubjectName { get; set; }
        public int? Semester { get; set; }
        public int? Year { get; set; }
        public string Objective { get; set; }
        public string Syllabus { get; set; }
        public string RefBooks { get; set; }
        [StringLength(50)]
        public string BedSubType { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [StringLength(50)]
        public string Language { get; set; }
        [StringLength(50)]
        public string Category { get; set; }
        [StringLength(50)]
        public string Course { get; set; }
        [StringLength(200)]
        public string MinQual { get; set; }
        public bool? SemesterWise { get; set; }
        [StringLength(100)]
        public string Seats { get; set; }
        [StringLength(200)]
        public string CourseType { get; set; }
        [StringLength(70)]
        public string DeptName { get; set; }
        public int? EstabYear { get; set; }
        [Column("CompanyID")]
        public int? CompanyId { get; set; }
        [StringLength(50)]
        public string ClassName { get; set; }
        [Column("ClassID")]
        public int? ClassId { get; set; }
        [StringLength(50)]
        public string ClassCode { get; set; }
        public bool? HasPractical { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}