// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class ClgListMediaDetailView
    {
        [Column("CompanyID")]
        public int? CompanyId { get; set; }
        [Column("MediaDetailID")]
        public int MediaDetailId { get; set; }
        [Column("ActivityID")]
        public int? ActivityId { get; set; }
        [Column("EventID")]
        public int? EventId { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(100)]
        public string EventName { get; set; }
        [StringLength(50)]
        public string EventType { get; set; }
        [StringLength(50)]
        public string CompCode { get; set; }
        public string DescriptionText { get; set; }
        public string Description { get; set; }
        [StringLength(100)]
        public string Nature { get; set; }
        [StringLength(50)]
        public string Place { get; set; }
        [StringLength(100)]
        public string UploadType { get; set; }
        public string Url { get; set; }
    }
}