// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class Committee
    {
        [Key]
        [Column("CommitteeID")]
        public int CommitteeId { get; set; }
        [Key]
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column("CompanyID")]
        public int? CompanyId { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public bool? IsManagement { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommSdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommEdate { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [Column("DescriptionHTML")]
        public string DescriptionHtml { get; set; }
        [StringLength(250)]
        public string DescriptionText { get; set; }
        [StringLength(50)]
        public string CommitteeCode { get; set; }
        public bool? NotListed { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [ForeignKey("TenantId,CompanyId")]
        [InverseProperty("Committee")]
        public virtual Company Company { get; set; }
    }
}