// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class DegreeCourse
    {
        [Key]
        [Column("DegreeCourseID")]
        public int DegreeCourseId { get; set; }
        [Key]
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [StringLength(50)]
        public string Course { get; set; }
        public bool? SemesterWise { get; set; }
        [StringLength(200)]
        public string MinQual { get; set; }
        [StringLength(100)]
        public string Seats { get; set; }
        [StringLength(500)]
        public string Fees { get; set; }
        [StringLength(200)]
        public string CourseType { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        public int? DurationMonth { get; set; }
        public int? DurationYear { get; set; }
        [Column("CompanyID")]
        public int? CompanyId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}