// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class FinYears
    {
        [Key]
        [Column("FinYearID")]
        public int FinYearId { get; set; }
        [Key]
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EnDate { get; set; }
        [StringLength(61)]
        public string Descrip { get; set; }
    }
}