// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class MediaDetail
    {
        [Key]
        [Column("MediaDetailID")]
        public int MediaDetailId { get; set; }
        [Key]
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column("ActivityID")]
        public int? ActivityId { get; set; }
        [Column("EventID")]
        public int? EventId { get; set; }
        [StringLength(100)]
        public string UploadType { get; set; }
        public string Url { get; set; }
    }
}