// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class NoticeBoard
    {
        [Key]
        [Column("NoticeBoardID")]
        public int NoticeBoardId { get; set; }
        [Key]
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [StringLength(100)]
        public string Heading { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Dated { get; set; }
        [Column("DeptID")]
        public int? DeptId { get; set; }
        [StringLength(400)]
        public string TextInternal { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string CreatedOn { get; set; }
        [Column("CompanyID")]
        public int? CompanyId { get; set; }
        [Column("DescripHTML")]
        public string DescripHtml { get; set; }
        public string DescripText { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [ForeignKey("TenantId,DeptId")]
        [InverseProperty("NoticeBoard")]
        public virtual Department Department { get; set; }
    }
}