// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class Subject
    {
        [Key]
        [Column("SubjectID")]
        public int SubjectId { get; set; }
        [Key]
        [Column("TenantID")]
        public Guid TenantId { get; set; }
        [Column("DeptID")]
        public int? DeptId { get; set; }
        [Column("ClassID")]
        public int? ClassId { get; set; }
        public string SubjectName { get; set; }
        public string Objective { get; set; }
        public string Syllabus { get; set; }
        public string RefBooks { get; set; }
        [StringLength(50)]
        public string BedSubType { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [StringLength(50)]
        public string Language { get; set; }
        [StringLength(50)]
        public string Category { get; set; }
        public bool? HasPractical { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}