// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Debug;
using risersoft.shared.dal;
using risersoft.shared.portable.Model;
using System;
using System.Data.Common;
namespace klts.app.mxform.admin.Mxcollegedb
{
    public partial class MxcollegedbContext : DbContext
    {
        public readonly Guid TenantId;
        public readonly string UserId, UserName, AppName, connectionString;
        //static LoggerFactory object
        public static readonly ILoggerFactory loggerFactory = new LoggerFactory(new[] {
              new DebugLoggerProvider()
        });
        public MxcollegedbContext(string strConn, RSCallerInfo info)
        {
            TenantId = info.UserAccount.AccountId;
            UserId = info.identity.Id.ToString();
            UserName = info.identity.UniqueName;
            AppName = info.AppHost.AppName;
            connectionString = strConn;
        }

        public override int SaveChanges()
        {
            ChangeTracker.UpdateRLSID("TenantID", TenantId);
            ChangeTracker.UpdateRLSID("TenantId", TenantId);
            ChangeTracker.UpdateUsers(UserId, UserName, AppName);
            return base.SaveChanges();
        }
        //https://github.com/dotnet/efcore/issues/15906
        private void Connection_StateChange(object sender, System.Data.StateChangeEventArgs e)
        {

            if (e.CurrentState == System.Data.ConnectionState.Open)
            {
                var senderConnection = (DbConnection)sender;
                senderConnection.SetSessionContext("TenantId", TenantId);
            }
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

            var connection = new SqlConnection(connectionString);
            connection.StateChange += Connection_StateChange;
            optionsBuilder.UseLoggerFactory(loggerFactory).
                UseSqlServer(connection);
        }
    }
}
//https://www.entityframeworktutorial.net/efcore/logging-in-entityframework-core.aspx